### ISSUE TITLE
Update it to hide Gmail counter

### ISSUE THREAD

**Issue by Smyled** [ngeldvis/No-Notif-Counter#4]
Thank you for building this extension.

Is it possible to hide notification count for Gmail as well ?

<img width="152" alt="2023-02-15_17-05-29" src="https://user-images.githubusercontent.com/10715031/219231926-09be6c4b-87d6-4e13-bfd6-0e331ebff3f7.png">

**Comment by ngeldvis** [comment]
Thank you for the suggestion. I added the feature and it's under review from the chrome web store. 
For now, if you'd like you can download the latest release and install the extension manually

**Comment by Smyled** [comment]
Wow, thanks a ton @ngeldvis. 

Suggestion: You might want to update the description and images on Chrome Extension Page. 

This app works on most websites that I have tried: Linkedin, Twitter.
